//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LINHDH-PC\\SQLEXPRESS;Initial Catalog=QuanLyPhatHanhTraiPhieu;User ID=" +
            "sa;Password=sa")]
        public string QuanLyPhatHanhTraiPhieuConnectionString {
            get {
                return ((string)(this["QuanLyPhatHanhTraiPhieuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BEO-PC\\SQLEXPRESS;Initial Catalog=QuanLyPhatHanhTraiPhieu;Integrated " +
            "Security=True")]
        public string QuanLyPhatHanhTraiPhieuConnectionString1 {
            get {
                return ((string)(this["QuanLyPhatHanhTraiPhieuConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=ADMIN_SOFT;Persist Security Info=True;Us" +
            "er ID=sa;Password=sa")]
        public string ADMIN_SOFTConnectionString {
            get {
                return ((string)(this["ADMIN_SOFTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUDM-PC\\SQLEXPRESS;Initial Catalog=BKI_QLDT;Persist Security Info=Tru" +
            "e;User ID=sa;Password=sa")]
        public string BKI_QLDTConnectionString {
            get {
                return ((string)(this["BKI_QLDTConnectionString"]));
            }
        }
    }
}
