//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccessQuanLyTaiSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOC_BAO_CAO
    {
        public decimal ID { get; set; }
        public string TEN_BAO_CAO { get; set; }
        public string DUONG_DAN { get; set; }
        public decimal ID_LOAI_TAI_SAN { get; set; }
        public decimal ID_LOAI_BAO_CAO { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual CM_DM_TU_DIEN CM_DM_TU_DIEN { get; set; }
        public virtual DM_LOAI_TAI_SAN DM_LOAI_TAI_SAN { get; set; }
    }
}
