//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccessQuanLyTaiSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_DE_NGHI_TRANG_CAP_DETAILS
    {
        public decimal ID { get; set; }
        public string MA_PHIEU { get; set; }
        public decimal ID_LOAI_TAI_SAN { get; set; }
        public decimal SO_LUONG { get; set; }
        public decimal ID_DON_VI_TINH { get; set; }
        public decimal ID_PHUONG_THUC { get; set; }
        public decimal DU_TOAN { get; set; }
        public decimal DU_TOAN_DUOC_DUYET { get; set; }
        public string MO_TA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DM_LOAI_TAI_SAN DM_LOAI_TAI_SAN { get; set; }
    }
}
