//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccessQuanLyTaiSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_TANG_GIAM_TAI_SAN
    {
        public decimal ID { get; set; }
        public string STT { get; set; }
        public Nullable<decimal> LEVEL_MODE { get; set; }
        public string USER_NAME { get; set; }
        public string TAI_SAN { get; set; }
        public Nullable<decimal> SO_DAU_KY_SO_LUONG { get; set; }
        public Nullable<decimal> SO_DAU_KY_DIEN_TICH { get; set; }
        public Nullable<decimal> SO_DAU_KY_NGUYEN_GIA { get; set; }
        public Nullable<decimal> SO_TANG_TRONG_KY_SO_LUONG { get; set; }
        public Nullable<decimal> SO_TANG_TRONG_KY_DIEN_TICH { get; set; }
        public Nullable<decimal> SO_TANG_TRONG_KY_NGUYEN_GIA { get; set; }
        public Nullable<decimal> SO_GIAM_TRONG_KY_SO_LUONG { get; set; }
        public Nullable<decimal> SO_GIAM_TRONG_KY_DIEN_TICH { get; set; }
        public Nullable<decimal> SO_GIAM_TRONG_KY_NGUYEN_GIA { get; set; }
        public Nullable<decimal> SO_CUOI_KY_SO_LUONG { get; set; }
        public Nullable<decimal> SO_CUOI_KY_DIEN_TICH { get; set; }
        public Nullable<decimal> SO_CUOI_KY_NGUYEN_GIA { get; set; }
        public string LOAI_HINH_DON_VI { get; set; }
        public string TEN_DON_VI { get; set; }
    }
}
