///************************************************
/// Generated by: TuDM
/// Date: 29/11/2014 11:18:56
/// Goal: Create User Service Class for DM_THONG_TIN_DON_VI
///************************************************
/// <summary>
/// Create User Service Class for DM_THONG_TIN_DON_VI
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS
{

	public class US_DM_THONG_TIN_DON_VI : US_Object
	{
		private const string c_TableName = "DM_THONG_TIN_DON_VI";
		#region "Public Properties"
		public decimal dcID
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()
		{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull()
		{
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_DON_VI
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI", IPConstants.c_DefaultDecimal);
			}
			set
			{
				pm_objDR["ID_DON_VI"] = value;
			}
		}

		public bool IsID_DON_VINull()
		{
			return pm_objDR.IsNull("ID_DON_VI");
		}

		public void SetID_DON_VINull()
		{
			pm_objDR["ID_DON_VI"] = System.Convert.DBNull;
		}

		public string strDIA_CHI
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "DIA_CHI", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["DIA_CHI"] = value;
			}
		}

		public bool IsDIA_CHINull()
		{
			return pm_objDR.IsNull("DIA_CHI");
		}

		public void SetDIA_CHINull()
		{
			pm_objDR["DIA_CHI"] = System.Convert.DBNull;
		}

		public string strKHO_BAC
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "KHO_BAC", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["KHO_BAC"] = value;
			}
		}

		public bool IsKHO_BACNull()
		{
			return pm_objDR.IsNull("KHO_BAC");
		}

		public void SetKHO_BACNull()
		{
			pm_objDR["KHO_BAC"] = System.Convert.DBNull;
		}

		public string strMA_TKKT1
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT1", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT1"] = value;
			}
		}

		public bool IsMA_TKKT1Null()
		{
			return pm_objDR.IsNull("MA_TKKT1");
		}

		public void SetMA_TKKT1Null()
		{
			pm_objDR["MA_TKKT1"] = System.Convert.DBNull;
		}

		public string strMA_DVQHNS
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_DVQHNS", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_DVQHNS"] = value;
			}
		}

		public bool IsMA_DVQHNSNull()
		{
			return pm_objDR.IsNull("MA_DVQHNS");
		}

		public void SetMA_DVQHNSNull()
		{
			pm_objDR["MA_DVQHNS"] = System.Convert.DBNull;
		}

		public string strMA_TKKT2
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT2", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT2"] = value;
			}
		}

		public bool IsMA_TKKT2Null()
		{
			return pm_objDR.IsNull("MA_TKKT2");
		}

		public void SetMA_TKKT2Null()
		{
			pm_objDR["MA_TKKT2"] = System.Convert.DBNull;
		}

		public string strMA_DVQHNS_1
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_DVQHNS_1", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_DVQHNS_1"] = value;
			}
		}

		public bool IsMA_DVQHNS_1Null()
		{
			return pm_objDR.IsNull("MA_DVQHNS_1");
		}

		public void SetMA_DVQHNS_1Null()
		{
			pm_objDR["MA_DVQHNS_1"] = System.Convert.DBNull;
		}

		public string strMA_DVQHNS_2
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_DVQHNS_2", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_DVQHNS_2"] = value;
			}
		}

		public bool IsMA_DVQHNS_2Null()
		{
			return pm_objDR.IsNull("MA_DVQHNS_2");
		}

		public void SetMA_DVQHNS_2Null()
		{
			pm_objDR["MA_DVQHNS_2"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_QBT_2
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_QBT_2", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_QBT_2"] = value;
			}
		}

		public bool IsMA_TKKT_QBT_2Null()
		{
			return pm_objDR.IsNull("MA_TKKT_QBT_2");
		}

		public void SetMA_TKKT_QBT_2Null()
		{
			pm_objDR["MA_TKKT_QBT_2"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_QBT_3
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_QBT_3", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_QBT_3"] = value;
			}
		}

		public bool IsMA_TKKT_QBT_3Null()
		{
			return pm_objDR.IsNull("MA_TKKT_QBT_3");
		}

		public void SetMA_TKKT_QBT_3Null()
		{
			pm_objDR["MA_TKKT_QBT_3"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_QBT_4
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_QBT_4", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_QBT_4"] = value;
			}
		}

		public bool IsMA_TKKT_QBT_4Null()
		{
			return pm_objDR.IsNull("MA_TKKT_QBT_4");
		}

		public void SetMA_TKKT_QBT_4Null()
		{
			pm_objDR["MA_TKKT_QBT_4"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_NS_2
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_NS_2", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_NS_2"] = value;
			}
		}

		public bool IsMA_TKKT_NS_2Null()
		{
			return pm_objDR.IsNull("MA_TKKT_NS_2");
		}

		public void SetMA_TKKT_NS_2Null()
		{
			pm_objDR["MA_TKKT_NS_2"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_NS_3
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_NS_3", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_NS_3"] = value;
			}
		}

		public bool IsMA_TKKT_NS_3Null()
		{
			return pm_objDR.IsNull("MA_TKKT_NS_3");
		}

		public void SetMA_TKKT_NS_3Null()
		{
			pm_objDR["MA_TKKT_NS_3"] = System.Convert.DBNull;
		}

		public string strMA_TKKT_NS_4
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT_NS_4", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT_NS_4"] = value;
			}
		}

		public bool IsMA_TKKT_NS_4Null()
		{
			return pm_objDR.IsNull("MA_TKKT_NS_4");
		}

		public void SetMA_TKKT_NS_4Null()
		{
			pm_objDR["MA_TKKT_NS_4"] = System.Convert.DBNull;
		}

		#endregion
		#region "Init Functions"
		public US_DM_THONG_TIN_DON_VI()
		{
			pm_objDS = new DS_DM_THONG_TIN_DON_VI();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_THONG_TIN_DON_VI(DataRow i_objDR)
			: this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_THONG_TIN_DON_VI(decimal i_dbID)
		{
			pm_objDS = new DS_DM_THONG_TIN_DON_VI();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

		#region Additional
		public void InitByID_DON_VI(decimal i_dbID_DON_VI)
		{
			pm_objDS = new DS_DM_THONG_TIN_DON_VI();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID_DON_VI", i_dbID_DON_VI, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		public bool isHaving_thong_tin_don_vi(decimal i_dbID_DON_VI)
		{
			pm_objDS = new DS_DM_THONG_TIN_DON_VI();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID_DON_VI", i_dbID_DON_VI, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			return (pm_objDS.Tables[0].Rows.Count != 0);
		}
		#endregion
	}
}
