///************************************************
/// Generated by: ThaiPH
/// Date: 05/12/2014 05:30:27
/// Goal: Create User Service Class for V_RPT_GD_GIAO_KH
///************************************************
/// <summary>
/// Create User Service Class for V_RPT_GD_GIAO_KH
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_V_RPT_GD_GIAO_KH : US_Object
{
	private const string c_TableName = "V_RPT_GD_GIAO_KH";
#region "Public Properties"
	public decimal dcID_QUYET_DINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_QUYET_DINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_QUYET_DINH"] = value;
		}
	}

	public bool IsID_QUYET_DINHNull()	{
		return pm_objDR.IsNull("ID_QUYET_DINH");
	}

	public void SetID_QUYET_DINHNull() {
		pm_objDR["ID_QUYET_DINH"] = System.Convert.DBNull;
	}

	public decimal dcID_DU_AN_CONG_TRINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DU_AN_CONG_TRINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DU_AN_CONG_TRINH"] = value;
		}
	}

	public bool IsID_DU_AN_CONG_TRINHNull()	{
		return pm_objDR.IsNull("ID_DU_AN_CONG_TRINH");
	}

	public void SetID_DU_AN_CONG_TRINHNull() {
		pm_objDR["ID_DU_AN_CONG_TRINH"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN_QUY_BT 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN_QUY_BT", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN_QUY_BT"] = value;
		}
	}

	public bool IsSO_TIEN_QUY_BTNull()	{
		return pm_objDR.IsNull("SO_TIEN_QUY_BT");
	}

	public void SetSO_TIEN_QUY_BTNull() {
		pm_objDR["SO_TIEN_QUY_BT"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN_NS 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN_NS", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN_NS"] = value;
		}
	}

	public bool IsSO_TIEN_NSNull()	{
		return pm_objDR.IsNull("SO_TIEN_NS");
	}

	public void SetSO_TIEN_NSNull() {
		pm_objDR["SO_TIEN_NS"] = System.Convert.DBNull;
	}

	public string strSO_QUYET_DINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_QUYET_DINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_QUYET_DINH"] = value;
		}
	}

	public bool IsSO_QUYET_DINHNull() 
	{
		return pm_objDR.IsNull("SO_QUYET_DINH");
	}

	public void SetSO_QUYET_DINHNull() {
		pm_objDR["SO_QUYET_DINH"] = System.Convert.DBNull;
	}

	public string strNOI_DUNG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NOI_DUNG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NOI_DUNG"] = value;
		}
	}

	public bool IsNOI_DUNGNull() 
	{
		return pm_objDR.IsNull("NOI_DUNG");
	}

	public void SetNOI_DUNGNull() {
		pm_objDR["NOI_DUNG"] = System.Convert.DBNull;
	}

	public string strTEN_DU_AN_CONG_TRINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DU_AN_CONG_TRINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DU_AN_CONG_TRINH"] = value;
		}
	}

	public bool IsTEN_DU_AN_CONG_TRINHNull() 
	{
		return pm_objDR.IsNull("TEN_DU_AN_CONG_TRINH");
	}

	public void SetTEN_DU_AN_CONG_TRINHNull() {
		pm_objDR["TEN_DU_AN_CONG_TRINH"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN"] = value;
		}
	}

	public bool IsSO_TIENNull()	{
		return pm_objDR.IsNull("SO_TIEN");
	}

	public void SetSO_TIENNull() {
		pm_objDR["SO_TIEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_RPT_GD_GIAO_KH() 
	{
		pm_objDS = new DS_V_RPT_GD_GIAO_KH();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_RPT_GD_GIAO_KH(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_RPT_GD_GIAO_KH(decimal i_dbID) 
	{
		pm_objDS = new DS_V_RPT_GD_GIAO_KH();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    public void FillDatasetTuNgayDenNgay(DS_V_RPT_GD_GIAO_KH v_ds, DateTime ip_dat_dau_nam, DateTime ip_dat_now)
    {
        CStoredProc v_cstore = new CStoredProc("pr_bao_cao_giao_kh");
        v_cstore.addDatetimeInputParam("@NGAY_DAU_NAM", ip_dat_dau_nam);
        v_cstore.addDatetimeInputParam("@NGAY_CUOI_NAM", ip_dat_now);
        v_cstore.fillDataSetByCommand(this, v_ds);
    }
}
}
