//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuToan.BaoCaoQT {


    public partial class BC_PL02_Kinh_phi_da_su_dung_de_nghi_quyet_toan {
    }
}
