//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuToan.BaoCaoQT
{


    public partial class BC_PL05_Danh_muc_giam_tru_quyet_toan
    {
    }
}
