// VBConversions Note: VB project level imports
using System;
using System.Drawing;
using System.Diagnostics;
using System.Data;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using IP.Core.IPData;
using IP.Core.IPBusinessService;
using IP.Core.IPCommon;

//************************************************
//* Generated by: IPC
//* Date: 18/11/2003
//* Goal: Create User Service Class for CM_DM_LOAI_TD
//************************************************


namespace IP.Core.IPUserService
{
	public class US_CM_DM_LOAI_TD : US_Object
	{
		
		private const string c_TableName = "CM_DM_LOAI_TD";
		
#region Public Property
		
public decimal dcID
		{
			get
			{
				return System.Convert.ToDecimal(pm_objDR["ID"]);
			}
			set
			{
				pm_objDR["ID"] = value;
			}
		}
		
public string strMA_LOAI
		{
			get
			{
				return System.Convert.ToString(pm_objDR["MA_LOAI"]);
			}
			set
			{
				pm_objDR["MA_LOAI"] = value;
			}
		}
		
public string strTEN_LOAI
		{
			get
			{
				return System.Convert.ToString(pm_objDR["TEN_LOAI"]);
			}
			set
			{
				pm_objDR["TEN_LOAI"] = value;
			}
		}
		
#endregion
		
		
		public US_CM_DM_LOAI_TD()
		{
			pm_objDS = new DS_CM_DM_LOAI_TD();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}
		
		public US_CM_DM_LOAI_TD(DataRow i_objDR) : this()
		{
			this.DataRow2Me(i_objDR);
		}
		
		public US_CM_DM_LOAI_TD(decimal i_dbID)
		{
			pm_objDS = new DS_CM_DM_LOAI_TD();
			pm_strTableName = c_TableName;
			this.FillDataset(pm_objDS, "Where ID = " + Conversion.Str(i_dbID));
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		
		public US_CM_DM_LOAI_TD(string i_strMaLoaiTD)
		{
			pm_objDS = new DS_CM_DM_LOAI_TD();
			pm_strTableName = c_TableName;
			
			System.Data.SqlClient.SqlCommand v_cmd = default(System.Data.SqlClient.SqlCommand);
			IMakeSelectCmd v_MakeSelCommand = default(IMakeSelectCmd);
			v_MakeSelCommand = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_MakeSelCommand.AddCondition("MA_LOAI", i_strMaLoaiTD, eKieuDuLieu.KieuString, eKieuSoSanh.Bang);
			v_cmd = v_MakeSelCommand.getSelectCmd();
			
			this.FillDatasetByCommand(pm_objDS, v_cmd);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		
		
#region Inner class
		public class MA_LOAI_TU_DIEN
		{
			public const string THANH_PHO_TINH = "TP"; //Thành phố - tỉnh
			public const string CAP_QUAN_LY = "CQL"; //Cấp quản lý
			public const string LOAI_TRUONG = "HTSH"; //Lọai trường
			public const string LOAI_PHAN_QUYEN = "LPQ"; //Loại phân quyền
			public const string LOAI_THAM_SO = "LTS"; //Lọai tham số
			public const string GIOI_TINH = "GT"; //Giới tính
			public const string TON_GIAO = "TOG"; //Tôn giáo
			public const string DAN_TOC = "DT"; //Dân tộc
			public const string LOAI_DIEM = "LOAI_DIEM"; //Loại điểm của bài thi và kiểm tra
			public const string TRANG_THAI_NAM_KH = "TT_NAM_KH"; //Trạng thái năm kế hoạch
			public const string TRANG_THAI_HK_KH = "TT_HK_KH"; //Trạng thái học kỳ kế hoạch
			public const string LOAI_DIEM_LT_HAY_TH = "LT_HAY_TH"; //Loại điểm lý thuyết hay thực hành
			public const string KHU_VUC_TUYEN_SINH = "KVTS"; //Khu vực tuyển sinh
			public const string DOI_TUONG_TUYEN_SINH = "DTTS"; //Đối tượng tuyển sinh
			public const string THANG_QUY_NAM = "TQN"; //Tháng,Quý,Năm
			public const string TRANG_THAI_SINH_VIEN = "TTSV"; //Trạng thái sinh viên
			public const string MA_LOAI_VAN_BANG = "MLVB"; //Mã loại văn bằng
			
		}
#endregion
		
	}
	
}
