//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataAccessQuanLyTaiSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_NguoiDungTrongNhomTruyCap
    {
        public string TEN_TRUY_CAP { get; set; }
        public string TEN { get; set; }
        public string MAT_KHAU { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public string NGUOI_TAO { get; set; }
        public Nullable<decimal> ID_DON_VI { get; set; }
        public string TEN_NHOM { get; set; }
        public string MA_NHOM { get; set; }
        public string MA_PHAN_HE { get; set; }
        public Nullable<decimal> NHOM_NGUOI_SU_DUNG_ID { get; set; }
        public Nullable<decimal> NGUOI_SU_DUNG_ID { get; set; }
        public decimal NHOM_DUOC_QUYEN_TRUY_CAP_ID { get; set; }
    }
}
