//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QUYET_DINH
    {
        public DM_QUYET_DINH()
        {
            this.GD_CHI_TIET_GIAO_KH = new HashSet<GD_CHI_TIET_GIAO_KH>();
            this.GD_CHI_TIET_GIAO_VON = new HashSet<GD_CHI_TIET_GIAO_VON>();
            this.GD_DU_TOAN_THU_CHI_PHI_PHA = new HashSet<GD_DU_TOAN_THU_CHI_PHI_PHA>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_DON_VI { get; set; }
        public string SO_QUYET_DINH { get; set; }
        public string NOI_DUNG { get; set; }
        public System.DateTime NGAY_THANG { get; set; }
        public decimal ID_LOAI_QUYET_DINH { get; set; }
        public decimal ID_LOAI_QUYET_DINH_GIAO { get; set; }
    
        public virtual CM_DM_TU_DIEN CM_DM_TU_DIEN { get; set; }
        public virtual CM_DM_TU_DIEN CM_DM_TU_DIEN1 { get; set; }
        public virtual DM_DON_VI DM_DON_VI { get; set; }
        public virtual ICollection<GD_CHI_TIET_GIAO_KH> GD_CHI_TIET_GIAO_KH { get; set; }
        public virtual ICollection<GD_CHI_TIET_GIAO_VON> GD_CHI_TIET_GIAO_VON { get; set; }
        public virtual ICollection<GD_DU_TOAN_THU_CHI_PHI_PHA> GD_DU_TOAN_THU_CHI_PHI_PHA { get; set; }
    }
}
