//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_PL04_DANH_MUC_CONG_TRINH_QUYET_TOAN
    {
        public decimal ID { get; set; }
        public string MA_SO { get; set; }
        public string TT { get; set; }
        public string CONG_TRINH_HANG_MUC { get; set; }
        public string MA_SO_PARENT { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public Nullable<decimal> GIA_TRI_DU_TOAN_CONG_TRINH_DUOC_DUYET { get; set; }
        public Nullable<decimal> GIA_TRI_CTHT_NAM_TRUOC_CON_NO_CHUYEN_NAM_NAY { get; set; }
        public Nullable<decimal> GIA_TRI_CTHT_NAM_NAY { get; set; }
        public Nullable<decimal> GIA_TRI_DE_NGHI_QUYET_TOAN_TRONG_NAM { get; set; }
        public Nullable<decimal> GIA_TRI_CTHT_DA_QUYET_TOAN_LK_DEN_NAM_BAO_CAO { get; set; }
        public Nullable<decimal> ID_DON_VI { get; set; }
        public Nullable<decimal> NAM { get; set; }
        public string CONG_THUC { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DM_DON_VI DM_DON_VI { get; set; }
    }
}
