//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_PL01_TONG_HOP_TINH_HINH_KINH_PHI_VA_QUYET_TOAN_CHI
    {
        public decimal ID { get; set; }
        public string MA_SO { get; set; }
        public string CHI_TIEU { get; set; }
        public string MA_SO_PARENT { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public Nullable<decimal> SO_BAO_CAO { get; set; }
        public Nullable<decimal> SO_XET_DUYET { get; set; }
        public string CONG_THUC { get; set; }
        public Nullable<decimal> ID_DON_VI { get; set; }
        public Nullable<decimal> NAM { get; set; }
    
        public virtual DM_DON_VI DM_DON_VI { get; set; }
    }
}
