//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_USER_GROUP
    {
        public HT_USER_GROUP()
        {
            this.HT_NGUOI_SU_DUNG = new HashSet<HT_NGUOI_SU_DUNG>();
            this.HT_QUAN_HE_SU_DUNG_DU_LIEU = new HashSet<HT_QUAN_HE_SU_DUNG_DU_LIEU>();
            this.HT_QUYEN_GROUP = new HashSet<HT_QUYEN_GROUP>();
        }
    
        public decimal ID { get; set; }
        public string USER_GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ID_DON_VI { get; set; }
    
        public virtual DM_DON_VI DM_DON_VI { get; set; }
        public virtual ICollection<HT_NGUOI_SU_DUNG> HT_NGUOI_SU_DUNG { get; set; }
        public virtual ICollection<HT_QUAN_HE_SU_DUNG_DU_LIEU> HT_QUAN_HE_SU_DUNG_DU_LIEU { get; set; }
        public virtual ICollection<HT_QUYEN_GROUP> HT_QUYEN_GROUP { get; set; }
    }
}
