//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_dm_quyet_dinh_so_don_vi_nhap_du_lieu
    {
        public decimal ID { get; set; }
        public decimal ID_DON_VI { get; set; }
        public string SO_QUYET_DINH { get; set; }
        public string NOI_DUNG { get; set; }
        public System.DateTime NGAY_THANG { get; set; }
        public decimal ID_LOAI_QUYET_DINH { get; set; }
        public decimal ID_LOAI_QUYET_DINH_GIAO { get; set; }
        public Nullable<int> SO_DON_VI { get; set; }
    }
}
