///************************************************
/// Generated by: TuDM
/// Date: 13/12/2014 02:21:28
/// Goal: Create User Service Class for DM_GIAI_NGAN
///************************************************
/// <summary>
/// Create User Service Class for DM_GIAI_NGAN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS
{

	public class US_DM_GIAI_NGAN : US_Object
	{
		private const string c_TableName = "DM_GIAI_NGAN";

		#region "Public Properties"
		public decimal dcID
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()
		{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull()
		{
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_DON_VI
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI", IPConstants.c_DefaultDecimal);
			}
			set
			{
				pm_objDR["ID_DON_VI"] = value;
			}
		}

		public bool IsID_DON_VINull()
		{
			return pm_objDR.IsNull("ID_DON_VI");
		}

		public void SetID_DON_VINull()
		{
			pm_objDR["ID_DON_VI"] = System.Convert.DBNull;
		}

		public DateTime datNGAY_THANG
		{
			get
			{
				return CNull.RowNVLDate(pm_objDR, "NGAY_THANG", IPConstants.c_DefaultDate);
			}
			set
			{
				pm_objDR["NGAY_THANG"] = value;
			}
		}

		public bool IsNGAY_THANGNull()
		{
			return pm_objDR.IsNull("NGAY_THANG");
		}

		public void SetNGAY_THANGNull()
		{
			pm_objDR["NGAY_THANG"] = System.Convert.DBNull;
		}

		public string strSO_UNC
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "SO_UNC", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["SO_UNC"] = value;
			}
		}

		public bool IsSO_UNCNull()
		{
			return pm_objDR.IsNull("SO_UNC");
		}

		public void SetSO_UNCNull()
		{
			pm_objDR["SO_UNC"] = System.Convert.DBNull;
		}

		public string strIS_NGUON_NS_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "IS_NGUON_NS_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["IS_NGUON_NS_YN"] = value;
			}
		}

		public bool IsIS_NGUON_NS_YNNull()
		{
			return pm_objDR.IsNull("IS_NGUON_NS_YN");
		}

		public void SetIS_NGUON_NS_YNNull()
		{
			pm_objDR["IS_NGUON_NS_YN"] = System.Convert.DBNull;
		}

		public string strMA_DVQHNS
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_DVQHNS", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_DVQHNS"] = value;
			}
		}

		public bool IsMA_DVQHNSNull()
		{
			return pm_objDR.IsNull("MA_DVQHNS");
		}

		public void SetMA_DVQHNSNull()
		{
			pm_objDR["MA_DVQHNS"] = System.Convert.DBNull;
		}

		public string strMA_CTMT_DA_HTCT
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_CTMT_DA_HTCT", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_CTMT_DA_HTCT"] = value;
			}
		}

		public bool IsMA_CTMT_DA_HTCTNull()
		{
			return pm_objDR.IsNull("MA_CTMT_DA_HTCT");
		}

		public void SetMA_CTMT_DA_HTCTNull()
		{
			pm_objDR["MA_CTMT_DA_HTCT"] = System.Convert.DBNull;
		}

		public string strNT_TEN_DON_VI
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_TEN_DON_VI", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_TEN_DON_VI"] = value;
			}
		}

		public bool IsNT_TEN_DON_VINull()
		{
			return pm_objDR.IsNull("NT_TEN_DON_VI");
		}

		public void SetNT_TEN_DON_VINull()
		{
			pm_objDR["NT_TEN_DON_VI"] = System.Convert.DBNull;
		}

		public string strNT_MA_SO_THUE
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_MA_SO_THUE", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_MA_SO_THUE"] = value;
			}
		}

		public bool IsNT_MA_SO_THUENull()
		{
			return pm_objDR.IsNull("NT_MA_SO_THUE");
		}

		public void SetNT_MA_SO_THUENull()
		{
			pm_objDR["NT_MA_SO_THUE"] = System.Convert.DBNull;
		}

		public string strNT_MA_NDKT
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_MA_NDKT", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_MA_NDKT"] = value;
			}
		}

		public bool IsNT_MA_NDKTNull()
		{
			return pm_objDR.IsNull("NT_MA_NDKT");
		}

		public void SetNT_MA_NDKTNull()
		{
			pm_objDR["NT_MA_NDKT"] = System.Convert.DBNull;
		}

		public string strNT_MA_CHUONG
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_MA_CHUONG", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_MA_CHUONG"] = value;
			}
		}

		public bool IsNT_MA_CHUONGNull()
		{
			return pm_objDR.IsNull("NT_MA_CHUONG");
		}

		public void SetNT_MA_CHUONGNull()
		{
			pm_objDR["NT_MA_CHUONG"] = System.Convert.DBNull;
		}

		public string strNT_CQ_QL_THU
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_CQ_QL_THU", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_CQ_QL_THU"] = value;
			}
		}

		public bool IsNT_CQ_QL_THUNull()
		{
			return pm_objDR.IsNull("NT_CQ_QL_THU");
		}

		public void SetNT_CQ_QL_THUNull()
		{
			pm_objDR["NT_CQ_QL_THU"] = System.Convert.DBNull;
		}

		public string strNT_MA_CQ_THU
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_MA_CQ_THU", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_MA_CQ_THU"] = value;
			}
		}

		public bool IsNT_MA_CQ_THUNull()
		{
			return pm_objDR.IsNull("NT_MA_CQ_THU");
		}

		public void SetNT_MA_CQ_THUNull()
		{
			pm_objDR["NT_MA_CQ_THU"] = System.Convert.DBNull;
		}

		public string strNT_KBNN_HACH_TOAN_KHOAN_THU
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_KBNN_HACH_TOAN_KHOAN_THU", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_KBNN_HACH_TOAN_KHOAN_THU"] = value;
			}
		}

		public bool IsNT_KBNN_HACH_TOAN_KHOAN_THUNull()
		{
			return pm_objDR.IsNull("NT_KBNN_HACH_TOAN_KHOAN_THU");
		}

		public void SetNT_KBNN_HACH_TOAN_KHOAN_THUNull()
		{
			pm_objDR["NT_KBNN_HACH_TOAN_KHOAN_THU"] = System.Convert.DBNull;
		}

		public string strNT_SO_TIEN_NOP_THUE
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NT_SO_TIEN_NOP_THUE", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NT_SO_TIEN_NOP_THUE"] = value;
			}
		}

		public bool IsNT_SO_TIEN_NOP_THUENull()
		{
			return pm_objDR.IsNull("NT_SO_TIEN_NOP_THUE");
		}

		public void SetNT_SO_TIEN_NOP_THUENull()
		{
			pm_objDR["NT_SO_TIEN_NOP_THUE"] = System.Convert.DBNull;
		}

		public string strTTDVH_DON_VI_NHAN_TIEN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_DON_VI_NHAN_TIEN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_DON_VI_NHAN_TIEN"] = value;
			}
		}

		public bool IsTTDVH_DON_VI_NHAN_TIENNull()
		{
			return pm_objDR.IsNull("TTDVH_DON_VI_NHAN_TIEN");
		}

		public void SetTTDVH_DON_VI_NHAN_TIENNull()
		{
			pm_objDR["TTDVH_DON_VI_NHAN_TIEN"] = System.Convert.DBNull;
		}

		public string strTTDVH_MA_DVQHNS
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_MA_DVQHNS", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_MA_DVQHNS"] = value;
			}
		}

		public bool IsTTDVH_MA_DVQHNSNull()
		{
			return pm_objDR.IsNull("TTDVH_MA_DVQHNS");
		}

		public void SetTTDVH_MA_DVQHNSNull()
		{
			pm_objDR["TTDVH_MA_DVQHNS"] = System.Convert.DBNull;
		}

		public string strTTDVH_DIA_CHI
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_DIA_CHI", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_DIA_CHI"] = value;
			}
		}

		public bool IsTTDVH_DIA_CHINull()
		{
			return pm_objDR.IsNull("TTDVH_DIA_CHI");
		}

		public void SetTTDVH_DIA_CHINull()
		{
			pm_objDR["TTDVH_DIA_CHI"] = System.Convert.DBNull;
		}

		public string strTTDVH_TAI_KHOAN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_TAI_KHOAN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_TAI_KHOAN"] = value;
			}
		}

		public bool IsTTDVH_TAI_KHOANNull()
		{
			return pm_objDR.IsNull("TTDVH_TAI_KHOAN");
		}

		public void SetTTDVH_TAI_KHOANNull()
		{
			pm_objDR["TTDVH_TAI_KHOAN"] = System.Convert.DBNull;
		}

		public string strTTDVH_MA_CTMT_DA_VA_HTCT
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_MA_CTMT_DA_VA_HTCT", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_MA_CTMT_DA_VA_HTCT"] = value;
			}
		}

		public bool IsTTDVH_MA_CTMT_DA_VA_HTCTNull()
		{
			return pm_objDR.IsNull("TTDVH_MA_CTMT_DA_VA_HTCT");
		}

		public void SetTTDVH_MA_CTMT_DA_VA_HTCTNull()
		{
			pm_objDR["TTDVH_MA_CTMT_DA_VA_HTCT"] = System.Convert.DBNull;
		}

		public string strTTDVH_KHO_BAC
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_KHO_BAC", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_KHO_BAC"] = value;
			}
		}

		public bool IsTTDVH_KHO_BACNull()
		{
			return pm_objDR.IsNull("TTDVH_KHO_BAC");
		}

		public void SetTTDVH_KHO_BACNull()
		{
			pm_objDR["TTDVH_KHO_BAC"] = System.Convert.DBNull;
		}

		public string strTTDVH_SO_TIEN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TTDVH_SO_TIEN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TTDVH_SO_TIEN"] = value;
			}
		}

		public bool IsTTDVH_SO_TIENNull()
		{
			return pm_objDR.IsNull("TTDVH_SO_TIEN");
		}

		public void SetTTDVH_SO_TIENNull()
		{
			pm_objDR["TTDVH_SO_TIEN"] = System.Convert.DBNull;
		}

		public string strTHUC_CHI_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "THUC_CHI_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["THUC_CHI_YN"] = value;
			}
		}

		public bool IsTHUC_CHI_YNNull()
		{
			return pm_objDR.IsNull("THUC_CHI_YN");
		}

		public void SetTHUC_CHI_YNNull()
		{
			pm_objDR["THUC_CHI_YN"] = System.Convert.DBNull;
		}

		public string strTAM_UNG_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TAM_UNG_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TAM_UNG_YN"] = value;
			}
		}

		public bool IsTAM_UNG_YNNull()
		{
			return pm_objDR.IsNull("TAM_UNG_YN");
		}

		public void SetTAM_UNG_YNNull()
		{
			pm_objDR["TAM_UNG_YN"] = System.Convert.DBNull;
		}

		public string strUNG_TRUOC_DU_DK_THANH_TOAN_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "UNG_TRUOC_DU_DK_THANH_TOAN_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["UNG_TRUOC_DU_DK_THANH_TOAN_YN"] = value;
			}
		}

		public bool IsUNG_TRUOC_DU_DK_THANH_TOAN_YNNull()
		{
			return pm_objDR.IsNull("UNG_TRUOC_DU_DK_THANH_TOAN_YN");
		}

		public void SetUNG_TRUOC_DU_DK_THANH_TOAN_YNNull()
		{
			pm_objDR["UNG_TRUOC_DU_DK_THANH_TOAN_YN"] = System.Convert.DBNull;
		}

		public string strUNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "UNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["UNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YN"] = value;
			}
		}

		public bool IsUNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YNNull()
		{
			return pm_objDR.IsNull("UNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YN");
		}

		public void SetUNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YNNull()
		{
			pm_objDR["UNG_TRUOC_CHUA_DU_DK_THANH_TOAN_YN"] = System.Convert.DBNull;
		}

		public string strCHUYEN_KHOAN_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "CHUYEN_KHOAN_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["CHUYEN_KHOAN_YN"] = value;
			}
		}

		public bool IsCHUYEN_KHOAN_YNNull()
		{
			return pm_objDR.IsNull("CHUYEN_KHOAN_YN");
		}

		public void SetCHUYEN_KHOAN_YNNull()
		{
			pm_objDR["CHUYEN_KHOAN_YN"] = System.Convert.DBNull;
		}

		public string strTIEN_MAT_YN
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TIEN_MAT_YN", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TIEN_MAT_YN"] = value;
			}
		}

		public bool IsTIEN_MAT_YNNull()
		{
			return pm_objDR.IsNull("TIEN_MAT_YN");
		}

		public void SetTIEN_MAT_YNNull()
		{
			pm_objDR["TIEN_MAT_YN"] = System.Convert.DBNull;
		}

		public string strMA_CAP_NS
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_CAP_NS", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_CAP_NS"] = value;
			}
		}

		public bool IsMA_CAP_NSNull()
		{
			return pm_objDR.IsNull("MA_CAP_NS");
		}

		public void SetMA_CAP_NSNull()
		{
			pm_objDR["MA_CAP_NS"] = System.Convert.DBNull;
		}

		public string strSO_CKC_HDK
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "SO_CKC_HDK", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["SO_CKC_HDK"] = value;
			}
		}

		public bool IsSO_CKC_HDKNull()
		{
			return pm_objDR.IsNull("SO_CKC_HDK");
		}

		public void SetSO_CKC_HDKNull()
		{
			pm_objDR["SO_CKC_HDK"] = System.Convert.DBNull;
		}

		public string strSO_CKC_HDTH
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "SO_CKC_HDTH", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["SO_CKC_HDTH"] = value;
			}
		}

		public bool IsSO_CKC_HDTHNull()
		{
			return pm_objDR.IsNull("SO_CKC_HDTH");
		}

		public void SetSO_CKC_HDTHNull()
		{
			pm_objDR["SO_CKC_HDTH"] = System.Convert.DBNull;
		}

		public string strTEN_CTMT_DA
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "TEN_CTMT_DA", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["TEN_CTMT_DA"] = value;
			}
		}

		public bool IsTEN_CTMT_DANull()
		{
			return pm_objDR.IsNull("TEN_CTMT_DA");
		}

		public void SetTEN_CTMT_DANull()
		{
			pm_objDR["TEN_CTMT_DA"] = System.Convert.DBNull;
		}

		public string strNGUOI_NHAN_TIEN_CMND_SO
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN_TIEN_CMND_SO", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NGUOI_NHAN_TIEN_CMND_SO"] = value;
			}
		}

		public bool IsNGUOI_NHAN_TIEN_CMND_SONull()
		{
			return pm_objDR.IsNull("NGUOI_NHAN_TIEN_CMND_SO");
		}

		public void SetNGUOI_NHAN_TIEN_CMND_SONull()
		{
			pm_objDR["NGUOI_NHAN_TIEN_CMND_SO"] = System.Convert.DBNull;
		}

		public string strNGUOI_NHAN_TIEN_CAP_NGAY
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN_TIEN_CAP_NGAY", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NGUOI_NHAN_TIEN_CAP_NGAY"] = value;
			}
		}

		public bool IsNGUOI_NHAN_TIEN_CAP_NGAYNull()
		{
			return pm_objDR.IsNull("NGUOI_NHAN_TIEN_CAP_NGAY");
		}

		public void SetNGUOI_NHAN_TIEN_CAP_NGAYNull()
		{
			pm_objDR["NGUOI_NHAN_TIEN_CAP_NGAY"] = System.Convert.DBNull;
		}

		public string strNGUOI_NHAN_TIEN_NOI_CAP
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "NGUOI_NHAN_TIEN_NOI_CAP", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["NGUOI_NHAN_TIEN_NOI_CAP"] = value;
			}
		}

		public bool IsNGUOI_NHAN_TIEN_NOI_CAPNull()
		{
			return pm_objDR.IsNull("NGUOI_NHAN_TIEN_NOI_CAP");
		}

		public void SetNGUOI_NHAN_TIEN_NOI_CAPNull()
		{
			pm_objDR["NGUOI_NHAN_TIEN_NOI_CAP"] = System.Convert.DBNull;
		}

		public string strMA_TKKT
		{
			get
			{
				return CNull.RowNVLString(pm_objDR, "MA_TKKT", IPConstants.c_DefaultString);
			}
			set
			{
				pm_objDR["MA_TKKT"] = value;
			}
		}

		public bool IsMA_TKKTNull()
		{
			return pm_objDR.IsNull("MA_TKKT");
		}

		public void SetMA_TKKTNull()
		{
			pm_objDR["MA_TKKT"] = System.Convert.DBNull;
		}

		#endregion
		#region "Init Functions"
		public US_DM_GIAI_NGAN()
		{
			pm_objDS = new DS_DM_GIAI_NGAN();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_GIAI_NGAN(DataRow i_objDR)
			: this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_GIAI_NGAN(decimal i_dbID)
		{
			pm_objDS = new DS_DM_GIAI_NGAN();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion

		#region "Additonal"
		public void get_dm_uy_nhiem_chi_by_don_vi_va_ngay_thang(DS_DM_GIAI_NGAN op_ds
			, decimal ip_dc_id_don_vi
			, DateTime ip_dat_tu_ngay
			, DateTime ip_dat_den_ngay
			, string ip_nguon_ns)
		{
			CStoredProc v_sp = new CStoredProc("pr_get_dm_uy_nhiem_chi_by_don_vi_va_ngay_thang");
			v_sp.addDecimalInputParam("@ip_dc_id_don_vi", ip_dc_id_don_vi);
			v_sp.addDatetimeInputParam("@ip_dat_tu_ngay", ip_dat_tu_ngay);
			v_sp.addDatetimeInputParam("@ip_dat_den_ngay", ip_dat_den_ngay);
			v_sp.addNVarcharInputParam("@ip_nguon_ns", ip_nguon_ns);
			v_sp.fillDataSetByCommand(this, op_ds);
		}

		public bool deleteAllDataOfUNC(decimal ip_dc_id_unc)
		{
			CStoredProc v_sp = new CStoredProc("pr_DM_GIAI_NGAN_deleteAllDataOfUNC");
			v_sp.addDecimalInputParam("@ip_dc_id_unc", ip_dc_id_unc);
			try
			{
				v_sp.ExecuteCommand(this);
				return true;
			}
			catch (Exception)
			{
				return false;
			}
			return false;
		}
		#endregion
	}
}
