///************************************************
/// Generated by: TuDM
/// Date: 10/11/2014 07:22:43
/// Goal: Create User Service Class for HT_LICH_SU_QLDT
///************************************************
/// <summary>
/// Create User Service Class for HT_LICH_SU_QLDT
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_HT_LICH_SU_QLDT : US_Object
{
	private const string c_TableName = "HT_LICH_SU_QLDT";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NGUOI_SU_DUNG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGUOI_SU_DUNG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGUOI_SU_DUNG"] = value;
		}
	}

	public bool IsID_NGUOI_SU_DUNGNull()	{
		return pm_objDR.IsNull("ID_NGUOI_SU_DUNG");
	}

	public void SetID_NGUOI_SU_DUNGNull() {
		pm_objDR["ID_NGUOI_SU_DUNG"] = System.Convert.DBNull;
	}

	public DateTime datTHOI_GIAN
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "THOI_GIAN", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["THOI_GIAN"] = value;
		}
	}

	public bool IsTHOI_GIANNull()
	{
		return pm_objDR.IsNull("THOI_GIAN");
	}

	public void SetTHOI_GIANNull()
	{
		pm_objDR["THOI_GIAN"] = System.Convert.DBNull;
	}

	public string strHANH_DONG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HANH_DONG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HANH_DONG"] = value;
		}
	}

	public bool IsHANH_DONGNull() 
	{
		return pm_objDR.IsNull("HANH_DONG");
	}

	public void SetHANH_DONGNull() {
		pm_objDR["HANH_DONG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_HT_LICH_SU_QLDT() 
	{
		pm_objDS = new DS_HT_LICH_SU_QLDT();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_HT_LICH_SU_QLDT(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_HT_LICH_SU_QLDT(decimal i_dbID) 
	{
		pm_objDS = new DS_HT_LICH_SU_QLDT();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
