//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GD_CHI_TIET_GIAO_VON
    {
        public string SO_QUYET_DINH { get; set; }
        public Nullable<decimal> SO_TIEN_QUY_BT { get; set; }
        public Nullable<decimal> ID_DON_VI { get; set; }
        public Nullable<decimal> ID { get; set; }
        public decimal ID_LOAI_QUYET_DINH { get; set; }
        public string TEN { get; set; }
    }
}
