//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_GROUP_QUYEN
    {
        public string Tên_nhóm { get; set; }
        public string Tên_truy_cập { get; set; }
        public string Tên { get; set; }
        public string Mật_khẩu { get; set; }
        public string Tên_chức_năng { get; set; }
    }
}
